#!/usr/bin/env bash
# This script transfers a file from a client machine to a server.
# scp command is used with the following arguments;
# - PATH_TO_FILE: to be copied to server, USER on server IP of server
# - IP: the IP address of the server.
# - USERNAME: the user to log in as.
# - SSH-KEY_PATH: path to ssh private key (IdentityFile) for authentication.
# - LOCATION: to copy into on the server.

if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -eq 3 ]
then
    scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
fi
